# --- RabbitMQ Connection Settings ---
# Basic connection details
RABBITMQ_HOST = 'localhost'  # Default: 'localhost'. Change if RabbitMQ runs elsewhere.
RABBITMQ_PORT = 5672         # Default RabbitMQ port.
RABBITMQ_VHOST = '/'           # Default virtual host.

# Credentials (optional, use defaults if not set in RabbitMQ)
# RABBITMQ_USER = 'guest'      # Default: 'guest'. Uncomment and change if needed.
# RABBITMQ_PASS = 'guest'      # Default: 'guest'. Uncomment and change if needed.


# --- Queue Names ---
# Define the queues used by the different agents in the processing pipeline.
# Ensure these names match across all agents that produce/consume from them.

# Queue for initial video paths sent by the orchestrator
VIDEO_QUEUE = 'video_processing_queue'

# Queue for paths to the generated transcription JSON files
TRANSCRIPTION_QUEUE = 'transcription_results_queue'

# Queue for paths to the ranked clips JSON files generated by the predictor
CLIPPING_QUEUE = 'clipping_results_queue'


# --- Folder Paths ---
# Define directories for storing intermediate and final results.
# Ensure these directories exist or the agents have permission to create them.

# Folder where the clip predictor agent saves its ranked clips JSON output
RESULTS_FOLDER = 'results'

# Folder for temporary files (e.g., extracted audio by transcription agent)
# Ensure this is cleaned up appropriately by the agents.
TEMP_FOLDER = 'temp_audio'

# Folder for final transcription outputs (used by transcription agent)
TRANSCRIPTION_OUTPUT_FOLDER = 'output_transcriptions'


# --- Optional: Other Settings ---
# Add any other shared configuration parameters needed by your agents below.
# Example: API keys loaded from environment variables with defaults
# OPEN_ROUTER_KEY = os.getenv("OPEN_ROUTER_KEY", None) # Agents should handle None case

